name: demo for runners
on:
  schedule:
    - cron: '*/2 * * * *'
  push:
    branches-ignore: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  runners:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "I have been triggered by ${{ github.event_name }} event."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: build maven project
        run: mvn clean compile package
      - name: display the fies
        run: |
          ls
          cd target
          ls
